theme: jekyll-theme-minimal
title: Zoher Kachwala
avatar: https://raw.githubusercontent.com/Zoher15/Zoher15.github.io/master/images/Zkachwal.jpeg
footer-links:
  email: zoher.kachwala@gmail.com
  facebook: https://www.facebook.com/zoher.kachwala
  instagram: https://www.instagram.com/zoher_15/
  linkedin: https://www.linkedin.com/in/zoher-kachwala/
  twitter: https://twitter.com/Zoher_15
